apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: unir-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unir-mongo
  namespace: unir-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unir-mongo
  template:
    metadata:
      labels:
        app: unir-mongo
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongo
        image: mongo:8.0.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: unir-mongo
  namespace: unir-namespace
  labels:
    app: unir-mongo
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: unir-mongo