apiVersion: apps/v1
kind: Deployment
metadata:
  name: unir-mongo-express
  namespace: unir-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unir-mongo-express
  template:
    metadata:
      labels:
        app: unir-mongo-express
    spec:
      automountServiceAccountToken: false
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          value: "unir-mongo"
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: unir-mongo-express
  namespace: unir-namespace
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 8081
  selector:
    app: unir-mongo-express