apiVersion: v1
kind: Service
metadata:
  name: unir-mongo-express
  namespace: unir-namespace
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 8081
  selector:
    app: unir-mongo-express