apiVersion: apps/v1
kind: Deployment
metadata:
  name: unir-mongo
  namespace: unir-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unir-mongo
  template:
    metadata:
      labels:
        app: unir-mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017